In [1]:
##  importar pandas e dados
import pandas as pd
import glob

In [23]:
## Teste: abrindo arquivo único e renomeando colunas com prefixo padrão

df = pd.read_csv("starnet_2014-12-31_flash.dat", sep="\s+",header=None, prefix="Coluna_" )
#df = pd.concat(map(pd.read_csv, glob.glob('starnet*.dat')),ignore_index=True, axis=1)

In [24]:
## Visualizando o arquivo aberto agora como dataframe - apenas 5 primeiras linhas
df.head()

,Coluna_0,Coluna_1,Coluna_2,Coluna_3,Coluna_4,Coluna_5,Coluna_6,Coluna_7,Coluna_8,Coluna_9,...,Coluna_21,Coluna_22,Coluna_23,Coluna_24,Coluna_25,Coluna_26,Coluna_27,Coluna_28,Coluna_29,Coluna_30
0,2014,12,31,10,10,31,728436,-15.79177,-49.93858,3.090,...,1,1,1,2,2.0,0.0,0.0,2.0,2.0,0.011541
1,2014,12,31,10,11,12,38983,-15.68356,-49.89305,2.573,...,1,0,0,0,0.0,0.0,0.0,1.0,1.0,0.000000
2,2014,12,31,10,13,20,832042,-15.69747,-49.84850,2.445,...,1,1,1,0,0.0,0.0,0.0,1.0,1.0,0.000000
3,2014,12,31,10,14,47,36785,-15.84778,-49.62569,5.633,...,0,0,1,0,1.0,0.0,0.0,1.0,1.0,0.000000
4,2014,12,31,10,14,47,8397,-15.75171,-49.89066,4.043,...,0,1,0,1,1.0,0.0,0.0,1.0,1.0,0.000000

In [6]:
## Teste: filtrando pela coluna 11 de qualidade e chamando apenas as colunas relevantes...
## Ano,mês,dia, hora, minuto, segundo, Latitude, Longitude, Qualidade
## Comando cria filtro, chamando dados relacionados à Coluna_11 igual a zero.
filtro1 = df[df.Coluna_11==0][["Coluna_0","Coluna_1","Coluna_2","Coluna_3","Coluna_4","Coluna_5","Coluna_7","Coluna_8","Coluna_11"]]
filtro1

,Coluna_0,Coluna_1,Coluna_2,Coluna_3,Coluna_4,Coluna_5,Coluna_7,Coluna_8,Coluna_11
0,2014,12,31,10,10,31,-15.79177,-49.93858,0
1,2014,12,31,10,11,12,-15.68356,-49.89305,0
2,2014,12,31,10,13,20,-15.69747,-49.84850,0
3,2014,12,31,10,14,47,-15.84778,-49.62569,0
5,2014,12,31,10,15,14,-15.77700,-49.91142,0
...,...,...,...,...,...,...,...,...,...
74087,2014,12,31,9,4,23,-17.34472,-46.50388,0
74088,2014,12,31,9,5,25,-17.30804,-46.42791,0
74090,2014,12,31,9,6,56,-17.16865,-46.21357,0
74092,2014,12,31,9,8,4,-17.35247,-46.13363,0
74094,2014,12,31,9,9,6,-17.18649,-46.25871,0

In [7]:
#código filtro dados

#extrair todos os arquivos na mesma pasta que python estiver rodando.
#trocar o ano no nome do arquivo csv
#o procedimento pode ser feito para cada mês também.

#importando módulos
import pandas as pd
import glob
#criar lista com os arquivos do ano
dados = glob.glob('starnet*.dat')
#loop para ler todos arquivos e filtrar pela Coluna 11 que são os dados de qualidade
for i in range(0,365):
    df = pd.read_csv(dados[i], sep="\s+",header=None, prefix="Coluna_" )
    filtro1 = dados2014[(dados2014.Coluna_11==0) & (dados2014.Coluna_7<=-19.49) & (dados2014.Coluna_7>=-20.39) & (dados2014.Coluna_8<=-43.56) & (dados2014.Coluna_8>=-44.67) ][["Coluna_0","Coluna_1","Coluna_2","Coluna_3","Coluna_4","Coluna_5","Coluna_7","Coluna_8","Coluna_11"]]
    #filtro1 = df[df.Coluna_11==0][["Coluna_0","Coluna_1","Coluna_2","Coluna_3","Coluna_4","Coluna_5","Coluna_7","Coluna_8","Coluna_11"]]
    filtro1.to_csv('%i_2014.csv' %i)
# juntando todos os arquivos criados no filtro e criar um arquivo csv com todos os dados do ano
dados2014 = pd.concat(map(pd.read_csv, glob.glob('*_2014.csv')),ignore_index=True, axis=0)
dados2014.to_csv('dados2014.csv',index=False)

In [30]:
filtro1 = dados2014[(dados2014.Coluna_11==0) & (dados2014.Coluna_7<=-19.49) & (dados2014.Coluna_7>=-20.39) & (dados2014.Coluna_8<=-43.56) & (dados2014.Coluna_8>=-44.67) ][["Coluna_0","Coluna_1","Coluna_2","Coluna_3","Coluna_4","Coluna_5","Coluna_7","Coluna_8","Coluna_11"]]

In [32]:
filtro1.to_csv('testelatitude.csv',index=False)

In [31]:
filtro1

,Coluna_0,Coluna_1,Coluna_2,Coluna_3,Coluna_4,Coluna_5,Coluna_7,Coluna_8,Coluna_11
18,2014,1,1,13,47,24,-19.61763,-43.72784,0
36,2014,1,1,13,52,4,-20.18537,-43.66860,0
37,2014,1,1,13,52,4,-20.19396,-43.85883,0
99,2014,1,1,14,15,50,-20.20153,-43.58931,0
101,2014,1,1,14,15,9,-20.22174,-43.81011,0
...,...,...,...,...,...,...,...,...,...
2918416,2014,1,10,21,54,24,-20.37761,-44.61329,0
2918758,2014,1,10,21,3,53,-20.34910,-44.65325,0
2918792,2014,1,10,21,4,51,-20.38214,-44.50539,0
2918843,2014,1,10,21,5,7,-20.37761,-44.45554,0
2919104,2014,1,10,22,13,5,-20.29297,-44.40936,0

In [27]:
dados

['starnet_2014-01-01_flash.dat',
 'starnet_2014-01-02_flash.dat',
 'starnet_2014-01-03_flash.dat',
 'starnet_2014-01-04_flash.dat',
 'starnet_2014-01-05_flash.dat',
 'starnet_2014-01-06_flash.dat',
 'starnet_2014-01-07_flash.dat',
 'starnet_2014-01-08_flash.dat',
 'starnet_2014-01-09_flash.dat',
 'starnet_2014-01-10_flash.dat',
 'starnet_2014-01-11_flash.dat',
 'starnet_2014-01-12_flash.dat',
 'starnet_2014-01-13_flash.dat',
 'starnet_2014-01-14_flash.dat',
 'starnet_2014-01-15_flash.dat',
 'starnet_2014-01-16_flash.dat',
 'starnet_2014-01-17_flash.dat',
 'starnet_2014-01-18_flash.dat',
 'starnet_2014-01-19_flash.dat',
 'starnet_2014-01-20_flash.dat',
 'starnet_2014-01-21_flash.dat',
 'starnet_2014-01-22_flash.dat',
 'starnet_2014-01-23_flash.dat',
 'starnet_2014-01-24_flash.dat',
 'starnet_2014-01-25_flash.dat',
 'starnet_2014-01-26_flash.dat',
 'starnet_2014-01-27_flash.dat',
 'starnet_2014-01-28_flash.dat',
 'starnet_2014-01-29_flash.dat',
 'starnet_2014-01-30_flash.dat',
 'starnet_2014-01-31_flash.dat',
 'starnet_2014-02-01_flash.dat',
 'starnet_2014-02-02_flash.dat',
 'starnet_2014-02-03_flash.dat',
 'starnet_2014-02-04_flash.dat',
 'starnet_2014-02-05_flash.dat',
 'starnet_2014-02-06_flash.dat',
 'starnet_2014-02-07_flash.dat',
 'starnet_2014-02-08_flash.dat',
 'starnet_2014-02-09_flash.dat',
 'starnet_2014-02-10_flash.dat',
 'starnet_2014-02-11_flash.dat',
 'starnet_2014-02-12_flash.dat',
 'starnet_2014-02-13_flash.dat',
 'starnet_2014-02-14_flash.dat',
 'starnet_2014-02-15_flash.dat',
 'starnet_2014-02-16_flash.dat',
 'starnet_2014-02-17_flash.dat',
 'starnet_2014-02-18_flash.dat',
 'starnet_2014-02-19_flash.dat',
 'starnet_2014-02-20_flash.dat',
 'starnet_2014-02-21_flash.dat',
 'starnet_2014-02-22_flash.dat',
 'starnet_2014-02-23_flash.dat',
 'starnet_2014-02-24_flash.dat',
 'starnet_2014-02-25_flash.dat',
 'starnet_2014-02-26_flash.dat',
 'starnet_2014-02-27_flash.dat',
 'starnet_2014-02-28_flash.dat',
 'starnet_2014-03-01_flash.dat',
 'starnet_2014-03-02_flash.dat',
 'starnet_2014-03-03_flash.dat',
 'starnet_2014-03-04_flash.dat',
 'starnet_2014-03-05_flash.dat',
 'starnet_2014-03-06_flash.dat',
 'starnet_2014-03-07_flash.dat',
 'starnet_2014-03-08_flash.dat',
 'starnet_2014-03-09_flash.dat',
 'starnet_2014-03-10_flash.dat',
 'starnet_2014-03-11_flash.dat',
 'starnet_2014-03-12_flash.dat',
 'starnet_2014-03-13_flash.dat',
 'starnet_2014-03-14_flash.dat',
 'starnet_2014-03-15_flash.dat',
 'starnet_2014-03-16_flash.dat',
 'starnet_2014-03-17_flash.dat',
 'starnet_2014-03-18_flash.dat',
 'starnet_2014-03-19_flash.dat',
 'starnet_2014-03-20_flash.dat',
 'starnet_2014-03-21_flash.dat',
 'starnet_2014-03-22_flash.dat',
 'starnet_2014-03-23_flash.dat',
 'starnet_2014-03-24_flash.dat',
 'starnet_2014-03-25_flash.dat',
 'starnet_2014-03-26_flash.dat',
 'starnet_2014-03-27_flash.dat',
 'starnet_2014-03-28_flash.dat',
 'starnet_2014-03-29_flash.dat',
 'starnet_2014-03-30_flash.dat',
 'starnet_2014-03-31_flash.dat',
 'starnet_2014-04-01_flash.dat',
 'starnet_2014-04-02_flash.dat',
 'starnet_2014-04-03_flash.dat',
 'starnet_2014-04-04_flash.dat',
 'starnet_2014-04-05_flash.dat',
 'starnet_2014-04-06_flash.dat',
 'starnet_2014-04-07_flash.dat',
 'starnet_2014-04-08_flash.dat',
 'starnet_2014-04-09_flash.dat',
 'starnet_2014-04-10_flash.dat',
 'starnet_2014-04-11_flash.dat',
 'starnet_2014-04-12_flash.dat',
 'starnet_2014-04-13_flash.dat',
 'starnet_2014-04-14_flash.dat',
 'starnet_2014-04-15_flash.dat',
 'starnet_2014-04-16_flash.dat',
 'starnet_2014-04-17_flash.dat',
 'starnet_2014-04-18_flash.dat',
 'starnet_2014-04-19_flash.dat',
 'starnet_2014-04-20_flash.dat',
 'starnet_2014-04-21_flash.dat',
 'starnet_2014-04-22_flash.dat',
 'starnet_2014-04-23_flash.dat',
 'starnet_2014-04-24_flash.dat',
 'starnet_2014-04-25_flash.dat',
 'starnet_2014-04-26_flash.dat',
 'starnet_2014-04-27_flash.dat',
 'starnet_2014-04-28_flash.dat',
 'starnet_2014-04-29_flash.dat',
 'starnet_2014-04-30_flash.dat',
 'starnet_2014-05-01_flash.dat',
 'starnet_2014-05-02_flash.dat',
 'starnet_2014-05-03_flash.dat',
 'starnet_2014-05-04_flash.dat',
 'starnet_2014-05-05_flash.dat',
 'starnet_2014-05-06_flash.dat',
 'starnet_2014-05-07_flash.dat',
 'starnet_2014-05-08_flash.dat',
 'starnet_2014-05-09_flash.dat',
 'starnet_2014-05-10_flash.dat',
 'starnet_2014-05-11_flash.dat',
 'starnet_2014-05-12_flash.dat',
 'starnet_2014-05-13_flash.dat',
 'starnet_2014-05-14_flash.dat',
 'starnet_2014-05-15_flash.dat',
 'starnet_2014-05-16_flash.dat',
 'starnet_2014-05-17_flash.dat',
 'starnet_2014-05-18_flash.dat',
 'starnet_2014-05-19_flash.dat',
 'starnet_2014-05-20_flash.dat',
 'starnet_2014-05-21_flash.dat',
 'starnet_2014-05-22_flash.dat',
 'starnet_2014-05-23_flash.dat',
 'starnet_2014-05-24_flash.dat',
 'starnet_2014-05-25_flash.dat',
 'starnet_2014-05-26_flash.dat',
 'starnet_2014-05-27_flash.dat',
 'starnet_2014-05-28_flash.dat',
 'starnet_2014-05-29_flash.dat',
 'starnet_2014-05-30_flash.dat',
 'starnet_2014-05-31_flash.dat',
 'starnet_2014-06-01_flash.dat',
 'starnet_2014-06-02_flash.dat',
 'starnet_2014-06-03_flash.dat',
 'starnet_2014-06-04_flash.dat',
 'starnet_2014-06-05_flash.dat',
 'starnet_2014-06-06_flash.dat',
 'starnet_2014-06-07_flash.dat',
 'starnet_2014-06-08_flash.dat',
 'starnet_2014-06-09_flash.dat',
 'starnet_2014-06-10_flash.dat',
 'starnet_2014-06-11_flash.dat',
 'starnet_2014-06-12_flash.dat',
 'starnet_2014-06-13_flash.dat',
 'starnet_2014-06-14_flash.dat',
 'starnet_2014-06-15_flash.dat',
 'starnet_2014-06-16_flash.dat',
 'starnet_2014-06-17_flash.dat',
 'starnet_2014-06-18_flash.dat',
 'starnet_2014-06-19_flash.dat',
 'starnet_2014-06-20_flash.dat',
 'starnet_2014-06-21_flash.dat',
 'starnet_2014-06-22_flash.dat',
 'starnet_2014-06-23_flash.dat',
 'starnet_2014-06-24_flash.dat',
 'starnet_2014-06-25_flash.dat',
 'starnet_2014-06-26_flash.dat',
 'starnet_2014-06-27_flash.dat',
 'starnet_2014-06-28_flash.dat',
 'starnet_2014-06-29_flash.dat',
 'starnet_2014-06-30_flash.dat',
 'starnet_2014-07-01_flash.dat',
 'starnet_2014-07-02_flash.dat',
 'starnet_2014-07-03_flash.dat',
 'starnet_2014-07-04_flash.dat',
 'starnet_2014-07-05_flash.dat',
 'starnet_2014-07-06_flash.dat',
 'starnet_2014-07-07_flash.dat',
 'starnet_2014-07-08_flash.dat',
 'starnet_2014-07-09_flash.dat',
 'starnet_2014-07-10_flash.dat',
 'starnet_2014-07-11_flash.dat',
 'starnet_2014-07-12_flash.dat',
 'starnet_2014-07-13_flash.dat',
 'starnet_2014-07-14_flash.dat',
 'starnet_2014-07-15_flash.dat',
 'starnet_2014-07-16_flash.dat',
 'starnet_2014-07-17_flash.dat',
 'starnet_2014-07-18_flash.dat',
 'starnet_2014-07-19_flash.dat',
 'starnet_2014-07-20_flash.dat',
 'starnet_2014-07-21_flash.dat',
 'starnet_2014-07-22_flash.dat',
 'starnet_2014-07-23_flash.dat',
 'starnet_2014-07-24_flash.dat',
 'starnet_2014-07-25_flash.dat',
 'starnet_2014-07-26_flash.dat',
 'starnet_2014-07-27_flash.dat',
 'starnet_2014-07-28_flash.dat',
 'starnet_2014-07-29_flash.dat',
 'starnet_2014-07-30_flash.dat',
 'starnet_2014-07-31_flash.dat',
 'starnet_2014-08-01_flash.dat',
 'starnet_2014-08-02_flash.dat',
 'starnet_2014-08-03_flash.dat',
 'starnet_2014-08-04_flash.dat',
 'starnet_2014-08-05_flash.dat',
 'starnet_2014-08-06_flash.dat',
 'starnet_2014-08-07_flash.dat',
 'starnet_2014-08-08_flash.dat',
 'starnet_2014-08-09_flash.dat',
 'starnet_2014-08-10_flash.dat',
 'starnet_2014-08-11_flash.dat',
 'starnet_2014-08-12_flash.dat',
 'starnet_2014-08-13_flash.dat',
 'starnet_2014-08-14_flash.dat',
 'starnet_2014-08-15_flash.dat',
 'starnet_2014-08-16_flash.dat',
 'starnet_2014-08-17_flash.dat',
 'starnet_2014-08-18_flash.dat',
 'starnet_2014-08-19_flash.dat',
 'starnet_2014-08-20_flash.dat',
 'starnet_2014-08-21_flash.dat',
 'starnet_2014-08-22_flash.dat',
 'starnet_2014-08-23_flash.dat',
 'starnet_2014-08-24_flash.dat',
 'starnet_2014-08-25_flash.dat',
 'starnet_2014-08-26_flash.dat',
 'starnet_2014-08-27_flash.dat',
 'starnet_2014-08-28_flash.dat',
 'starnet_2014-08-29_flash.dat',
 'starnet_2014-08-30_flash.dat',
 'starnet_2014-08-31_flash.dat',
 'starnet_2014-09-01_flash.dat',
 'starnet_2014-09-02_flash.dat',
 'starnet_2014-09-03_flash.dat',
 'starnet_2014-09-04_flash.dat',
 'starnet_2014-09-05_flash.dat',
 'starnet_2014-09-06_flash.dat',
 'starnet_2014-09-07_flash.dat',
 'starnet_2014-09-08_flash.dat',
 'starnet_2014-09-09_flash.dat',
 'starnet_2014-09-10_flash.dat',
 'starnet_2014-09-11_flash.dat',
 'starnet_2014-09-12_flash.dat',
 'starnet_2014-09-13_flash.dat',
 'starnet_2014-09-14_flash.dat',
 'starnet_2014-09-15_flash.dat',
 'starnet_2014-09-16_flash.dat',
 'starnet_2014-09-17_flash.dat',
 'starnet_2014-09-18_flash.dat',
 'starnet_2014-09-19_flash.dat',
 'starnet_2014-09-20_flash.dat',
 'starnet_2014-09-21_flash.dat',
 'starnet_2014-09-22_flash.dat',
 'starnet_2014-09-23_flash.dat',
 'starnet_2014-09-24_flash.dat',
 'starnet_2014-09-25_flash.dat',
 'starnet_2014-09-26_flash.dat',
 'starnet_2014-09-27_flash.dat',
 'starnet_2014-09-28_flash.dat',
 'starnet_2014-09-29_flash.dat',
 'starnet_2014-09-30_flash.dat',
 'starnet_2014-10-01_flash.dat',
 'starnet_2014-10-02_flash.dat',
 'starnet_2014-10-03_flash.dat',
 'starnet_2014-10-04_flash.dat',
 'starnet_2014-10-05_flash.dat',
 'starnet_2014-10-06_flash.dat',
 'starnet_2014-10-07_flash.dat',
 'starnet_2014-10-08_flash.dat',
 'starnet_2014-10-09_flash.dat',
 'starnet_2014-10-10_flash.dat',
 'starnet_2014-10-11_flash.dat',
 'starnet_2014-10-12_flash.dat',
 'starnet_2014-10-13_flash.dat',
 'starnet_2014-10-14_flash.dat',
 'starnet_2014-10-15_flash.dat',
 'starnet_2014-10-16_flash.dat',
 'starnet_2014-10-17_flash.dat',
 'starnet_2014-10-18_flash.dat',
 'starnet_2014-10-19_flash.dat',
 'starnet_2014-10-20_flash.dat',
 'starnet_2014-10-21_flash.dat',
 'starnet_2014-10-22_flash.dat',
 'starnet_2014-10-23_flash.dat',
 'starnet_2014-10-24_flash.dat',
 'starnet_2014-10-25_flash.dat',
 'starnet_2014-10-26_flash.dat',
 'starnet_2014-10-27_flash.dat',
 'starnet_2014-10-28_flash.dat',
 'starnet_2014-10-29_flash.dat',
 'starnet_2014-10-30_flash.dat',
 'starnet_2014-10-31_flash.dat',
 'starnet_2014-11-01_flash.dat',
 'starnet_2014-11-02_flash.dat',
 'starnet_2014-11-03_flash.dat',
 'starnet_2014-11-04_flash.dat',
 'starnet_2014-11-05_flash.dat',
 'starnet_2014-11-06_flash.dat',
 'starnet_2014-11-07_flash.dat',
 'starnet_2014-11-08_flash.dat',
 'starnet_2014-11-09_flash.dat',
 'starnet_2014-11-10_flash.dat',
 'starnet_2014-11-11_flash.dat',
 'starnet_2014-11-12_flash.dat',
 'starnet_2014-11-13_flash.dat',
 'starnet_2014-11-14_flash.dat',
 'starnet_2014-11-15_flash.dat',
 'starnet_2014-11-16_flash.dat',
 'starnet_2014-11-17_flash.dat',
 'starnet_2014-11-18_flash.dat',
 'starnet_2014-11-19_flash.dat',
 'starnet_2014-11-20_flash.dat',
 'starnet_2014-11-21_flash.dat',
 'starnet_2014-11-22_flash.dat',
 'starnet_2014-11-23_flash.dat',
 'starnet_2014-11-24_flash.dat',
 'starnet_2014-11-25_flash.dat',
 'starnet_2014-11-26_flash.dat',
 'starnet_2014-11-27_flash.dat',
 'starnet_2014-11-28_flash.dat',
 'starnet_2014-11-29_flash.dat',
 'starnet_2014-11-30_flash.dat',
 'starnet_2014-12-01_flash.dat',
 'starnet_2014-12-02_flash.dat',
 'starnet_2014-12-03_flash.dat',
 'starnet_2014-12-04_flash.dat',
 'starnet_2014-12-05_flash.dat',
 'starnet_2014-12-06_flash.dat',
 'starnet_2014-12-07_flash.dat',
 'starnet_2014-12-08_flash.dat',
 'starnet_2014-12-09_flash.dat',
 'starnet_2014-12-10_flash.dat',
 'starnet_2014-12-11_flash.dat',
 'starnet_2014-12-12_flash.dat',
 'starnet_2014-12-13_flash.dat',
 'starnet_2014-12-14_flash.dat',
 'starnet_2014-12-15_flash.dat',
 'starnet_2014-12-16_flash.dat',
 'starnet_2014-12-17_flash.dat',
 'starnet_2014-12-18_flash.dat',
 'starnet_2014-12-19_flash.dat',
 'starnet_2014-12-20_flash.dat',
 'starnet_2014-12-21_flash.dat',
 'starnet_2014-12-22_flash.dat',
 'starnet_2014-12-23_flash.dat',
 'starnet_2014-12-24_flash.dat',
 'starnet_2014-12-25_flash.dat',
 'starnet_2014-12-26_flash.dat',
 'starnet_2014-12-27_flash.dat',
 'starnet_2014-12-28_flash.dat',
 'starnet_2014-12-29_flash.dat',
 'starnet_2014-12-30_flash.dat',
 'starnet_2014-12-31_flash.dat']